name: C++ CI on github

on: [push]

jobs:
  build-on-push:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build & Test
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror -O2 -fsanitize=address,undefined,thread"
        cmake --build build
        cd build
        ctest --output-on-failure
